
export const auth = {
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
  AUTH_LOGIN_PENDING: "AUTH_LOGIN_PENDING",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_LOGOUT_ERROR: "AUTH_LOGOUT_ERROR",
  AUTH_LOGOUT_PENDING: "AUTH_LOGOUT_PENDING",
  AUTH_AUTHORIZE_SUCCESS: "AUTH_AUTHORIZE_SUCCESS",
  AUTH_AUTHORIZE_ERROR: "AUTH_AUTHORIZE_ERROR",
  AUTH_AUTHORIZE_PENDING: "AUTH_AUTHORIZE_PENDING",
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_REGISTER_ERROR: "AUTH_REGISTER_ERROR",
  AUTH_REGISTER_PENDING: "AUTH_REGISTER_PENDING",
}

export const adminAuth = {
  ADMIN_AUTH_LOGIN_SUCCESS: "ADMIN_AUTH_LOGIN_SUCCESS",
  ADMIN_AUTH_LOGIN_ERROR: "ADMIN_AUTH_LOGIN_ERROR",
  ADMIN_AUTH_LOGIN_PENDING: "ADMIN_AUTH_LOGIN_PENDING",
  ADMIN_AUTH_LOGOUT_SUCCESS: "ADMIN_AUTH_LOGOUT_SUCCESS",
  ADMIN_AUTH_LOGOUT_ERROR: "ADMIN_AUTH_LOGOUT_ERROR",
  ADMIN_AUTH_LOGOUT_PENDING: "ADMIN_AUTH_LOGOUT_PENDING",
  ADMIN_AUTH_AUTHORIZE_SUCCESS: "ADMIN_AUTH_AUTHORIZE_SUCCESS",
  ADMIN_AUTH_AUTHORIZE_ERROR: "ADMIN_AUTH_AUTHORIZE_ERROR",
  ADMIN_AUTH_AUTHORIZE_PENDING: "ADMIN_AUTH_AUTHORIZE_PENDING",
}

export const adminProductsCountStat = {
  GET_ADMIN_PRODUCTS_COUNT_STAT_SUCCESS: "GET_ADMIN_PRODUCTS_COUNT_STAT_SUCCESS",
  GET_ADMIN_PRODUCTS_COUNT_STAT_ERROR: "GET_ADMIN_PRODUCTS_COUNT_STAT_ERROR",
  GET_ADMIN_PRODUCTS_COUNT_STAT_PENDING: "GET_ADMIN_PRODUCTS_COUNT_STAT_PENDING",
}

export const adminPastMonthOrdersCountStat = {
  GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_SUCCESS: "GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_SUCCESS",
  GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_ERROR: "GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_ERROR",
  GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_PENDING: "GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_PENDING",
}

export const adminOngoingShipmentsPercentageStat = {
  GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_SUCCESS: "GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_SUCCESS",
  GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_ERROR: "GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_ERROR",
  GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_PENDING: "GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_PENDING",
}

export const adminGuestUsersCountStat = {
  GET_ADMIN_GUEST_USERS_COUNT_STAT_SUCCESS: "GET_ADMIN_GUEST_USERS_COUNT_STAT_SUCCESS",
  GET_ADMIN_GUEST_USERS_COUNT_STAT_ERROR: "GET_ADMIN_GUEST_USERS_COUNT_STAT_ERROR",
  GET_ADMIN_GUEST_USERS_COUNT_STAT_PENDING: "GET_ADMIN_GUEST_USERS_COUNT_STAT_PENDING",
}

export const adminEarningsLineChart = {
  GET_ADMIN_EARNINGS_LINE_CHART_SUCCESS: "GET_ADMIN_EARNINGS_LINE_CHART_SUCCESS",
  GET_ADMIN_EARNINGS_LINE_CHART_ERROR: "GET_ADMIN_EARNINGS_LINE_CHART_ERROR",
  GET_ADMIN_EARNINGS_LINE_CHART_PENDING: "GET_ADMIN_EARNINGS_LINE_CHART_PENDING",
}

export const adminOrdersBarChart = {
  GET_ADMIN_ORDERS_BAR_CHART_SUCCESS: "GET_ADMIN_ORDERS_BAR_CHART_SUCCESS",
  GET_ADMIN_ORDERS_BAR_CHART_ERROR: "GET_ADMIN_ORDERS_BAR_CHART_ERROR",
  GET_ADMIN_ORDERS_BAR_CHART_PENDING: "GET_ADMIN_ORDERS_BAR_CHART_PENDING",
}

export const adminSearchProducts = {
  GET_ADMIN_SEARCH_PRODUCTS_SUCCESS: "GET_ADMIN_SEARCH_PRODUCTS_SUCCESS",
  GET_ADMIN_SEARCH_PRODUCTS_ERROR: "GET_ADMIN_SEARCH_PRODUCTS_ERROR",
  GET_ADMIN_SEARCH_PRODUCTS_PENDING: "GET_ADMIN_SEARCH_PRODUCTS_PENDING",
}

export const adminProduct = {
  GET_ADMIN_PRODUCT_SUCCESS: "GET_ADMIN_PRODUCT_SUCCESS",
  GET_ADMIN_PRODUCT_ERROR: "GET_ADMIN_PRODUCT_ERROR",
  GET_ADMIN_PRODUCT_PENDING: "GET_ADMIN_PRODUCT_PENDING",
}

export const adminDeleteProduct = {
  DELETE_ADMIN_PRODUCT_SUCCESS: "DELETE_ADMIN_PRODUCT_SUCCESS",
  DELETE_ADMIN_PRODUCT_ERROR: "DELETE_ADMIN_PRODUCT_ERROR",
  DELETE_ADMIN_PRODUCT_PENDING: "DELETE_ADMIN_PRODUCT_PENDING",
}

export const adminCategories = {
  GET_ADMIN_CATEGORIES_SUCCESS: "GET_ADMIN_CATEGORIES_SUCCESS",
  GET_ADMIN_CATEGORIES_ERROR: "GET_ADMIN_CATEGORIES_ERROR",
  GET_ADMIN_CATEGORIES_PENDING: "GET_ADMIN_CATEGORIES_PENDING",
}

export const adminManufacturers = {
  GET_ADMIN_MANUFACTURERS_SUCCESS: "GET_ADMIN_MANUFACTURERS_SUCCESS",
  GET_ADMIN_MANUFACTURERS_ERROR: "GET_ADMIN_MANUFACTURERS_ERROR",
  GET_ADMIN_MANUFACTURERS_PENDING: "GET_ADMIN_MANUFACTURERS_PENDING",
}

export const adminNewProduct = {
  CREATE_ADMIN_PRODUCT_SUCCESS: "CREATE_ADMIN_PRODUCT_SUCCESS",
  CREATE_ADMIN_PRODUCT_ERROR: "CREATE_ADMIN_PRODUCT_ERROR",
  CREATE_ADMIN_PRODUCT_PENDING: "CREATE_ADMIN_PRODUCT_PENDING",
}

export const products = {
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
  GET_PRODUCTS_PENDING: "GET_PRODUCTS_PENDING",
}

export const product = {
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
  GET_PRODUCT_PENDING: "GET_PRODUCT_PENDING",
}