
export const auth = {
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
  AUTH_LOGIN_PENDING: "AUTH_LOGIN_PENDING",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_LOGOUT_ERROR: "AUTH_LOGOUT_ERROR",
  AUTH_LOGOUT_PENDING: "AUTH_LOGOUT_PENDING",
  AUTH_AUTHORIZE_SUCCESS: "AUTH_AUTHORIZE_SUCCESS",
  AUTH_AUTHORIZE_ERROR: "AUTH_AUTHORIZE_ERROR",
  AUTH_AUTHORIZE_PENDING: "AUTH_AUTHORIZE_PENDING",
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_REGISTER_ERROR: "AUTH_REGISTER_ERROR",
  AUTH_REGISTER_PENDING: "AUTH_REGISTER_PENDING",
}

export const users = {
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_ERROR: "GET_USERS_ERROR",
  GET_USERS_PENDING: "GET_USERS_PENDING",
}

export const adminAuth = {
  ADMIN_AUTH_LOGIN_SUCCESS: "ADMIN_AUTH_LOGIN_SUCCESS",
  ADMIN_AUTH_LOGIN_ERROR: "ADMIN_AUTH_LOGIN_ERROR",
  ADMIN_AUTH_LOGIN_PENDING: "ADMIN_AUTH_LOGIN_PENDING",
  ADMIN_AUTH_LOGOUT_SUCCESS: "ADMIN_AUTH_LOGOUT_SUCCESS",
  ADMIN_AUTH_LOGOUT_ERROR: "ADMIN_AUTH_LOGOUT_ERROR",
  ADMIN_AUTH_LOGOUT_PENDING: "ADMIN_AUTH_LOGOUT_PENDING",
  ADMIN_AUTH_AUTHORIZE_SUCCESS: "ADMIN_AUTH_AUTHORIZE_SUCCESS",
  ADMIN_AUTH_AUTHORIZE_ERROR: "ADMIN_AUTH_AUTHORIZE_ERROR",
  ADMIN_AUTH_AUTHORIZE_PENDING: "ADMIN_AUTH_AUTHORIZE_PENDING",
}

export const adminProductsCountStat = {
  GET_ADMIN_PRODUCTS_COUNT_STAT_SUCCESS: "GET_ADMIN_PRODUCTS_COUNT_STAT_SUCCESS",
  GET_ADMIN_PRODUCTS_COUNT_STAT_ERROR: "GET_ADMIN_PRODUCTS_COUNT_STAT_ERROR",
  GET_ADMIN_PRODUCTS_COUNT_STAT_PENDING: "GET_ADMIN_PRODUCTS_COUNT_STAT_PENDING",
}

export const adminPastMonthOrdersCountStat = {
  GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_SUCCESS: "GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_SUCCESS",
  GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_ERROR: "GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_ERROR",
  GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_PENDING: "GET_ADMIN_PAST_MONTH_ORDERS_COUNT_STAT_PENDING",
}

export const adminOngoingShipmentsPercentageStat = {
  GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_SUCCESS: "GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_SUCCESS",
  GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_ERROR: "GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_ERROR",
  GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_PENDING: "GET_ADMIN_ONGOING_SHIPMENTS_PERCENTAGE_STAT_PENDING",
}

export const adminGuestUsersCountStat = {
  GET_ADMIN_GUEST_USERS_COUNT_STAT_SUCCESS: "GET_ADMIN_GUEST_USERS_COUNT_STAT_SUCCESS",
  GET_ADMIN_GUEST_USERS_COUNT_STAT_ERROR: "GET_ADMIN_GUEST_USERS_COUNT_STAT_ERROR",
  GET_ADMIN_GUEST_USERS_COUNT_STAT_PENDING: "GET_ADMIN_GUEST_USERS_COUNT_STAT_PENDING",
}

export const adminEarningsLineChart = {
  GET_ADMIN_EARNINGS_LINE_CHART_SUCCESS: "GET_ADMIN_EARNINGS_LINE_CHART_SUCCESS",
  GET_ADMIN_EARNINGS_LINE_CHART_ERROR: "GET_ADMIN_EARNINGS_LINE_CHART_ERROR",
  GET_ADMIN_EARNINGS_LINE_CHART_PENDING: "GET_ADMIN_EARNINGS_LINE_CHART_PENDING",
}
